### ISSUE TITLE
Unresolved SqlJet dependency

### ISSUE THREAD

**Issue by mb720** [ari/gradle-release-plugin#20]
Hi,

```
Could not resolve all dependencies for configuration ':classpath'.
   > Could not find org.tmatesoft.sqljet:sqljet:1.1.8-SNAPSHOT.
     Required by:
         :GradleFx:unspecified > au.com.ish.gradle:release:2.2.2 > org.tmatesoft
.svnkit:svnkit:1.8.0
```

This is what I get after invoking `gradle tasks` when I have added this to my `build.gradle`:

```
buildscript {
  repositories {
    mavenCentral()
    maven {
      url 'http://maven.tmatesoft.com/content/repositories/releases/'
    }
  }

  dependencies {
    classpath 'au.com.ish.gradle:release:2.2.2'
  }
}

apply plugin: 'release'
```

**Comment by greenscar** [comment]
This should not be closed. I have to enable SNAPSHOT plugins in order to have this work.

**Comment by pkovalenko** [comment]
I have almost the same issue

> Could not resolve all dependencies for configuration ':app:classpath'.
   > Could not resolve org.tmatesoft.svnkit:svnkit:1.8.0.
     Required by:
         Insight_Android_Release:app:1.0 > au.com.ish.gradle:release:2.2.2
      > Could not resolve org.tmatesoft.svnkit:svnkit:1.8.0.
         > Could not get resource 'http://maven.tmatesoft.com/content/repositories/releases/org/tmatesoft/svnkit/svnkit/1.8.0/svnkit-1.8.0.pom'.
            > Could not GET 'http://maven.tmatesoft.com/content/repositories/releases/org/tmatesoft/svnkit/svnkit/1.8.0/svnkit-1.8.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

How I can resolve this?
Thank you
