### ISSUE TITLE
Release plugin version 2.2.2 depends on sqljet 1.1.8-SNAPSHOT

### ISSUE THREAD

**Issue by prokod** [ari/gradle-release-plugin#25]
Hi there,

First I would like to say that this plugin is simple to use! thanks for that and for the plugin at first place.
I am building a gradle wrapper plugin that uses release plugin and I noticed that it tries to fetch sqljet 1.1.8-SNAPSHOT I think this should be using a released version of that lib and not its SNAPSHOT one.

**Comment by greenscar** [comment]
au.com.ish.gradle:release:2.2.2 > org.tmatesoft.svnkit:svnkit:1.8.0 > org.tmatesoft.sqljet:sqljet:1.1.8-SNAPSHOT

the release plugin needs to depend on a newer version of svnkit.

**Comment by Xerosigma** [comment]
Having a related problem. Gradle won't perform a project refresh because of it:

Error:Could not find org.tmatesoft.sqljet:sqljet:1.1.8-SNAPSHOT.
Searched in the following locations:
....
...
...
Required by:
    :clientapp:unspecified > au.com.ish.gradle:release:2.2.2 > org.tmatesoft.svnkit:svnkit:1.8.0

**Comment by ari** [comment]
svnkit upgraded, thanks

**Comment by gokceng** [comment]
Hi Ari,
I am trying to use `au.com.ish.gradle:release:2.2.2` but I am getting same error still:
`* What went wrong:
A problem occurred configuring root project 'recentSearches'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve org.tmatesoft.sqljet:sqljet:1.1.8-SNAPSHOT.
     Required by:
         :recentSearches:unspecified > au.com.ish.gradle:release:2.2.2 > org.tmatesoft.svnkit:svnkit:1.8.0
      > Could not resolve org.tmatesoft.sqljet:sqljet:1.1.8-SNAPSHOT.
         > Unable to load Maven meta-data from https://maven.tmatesoft.com/content/repositories/releases/org/tmatesoft/sqljet/sqljet/1.1.8-SNAPSHOT/maven-metadata.xml.
            > Could not GET 'https://maven.tmatesoft.com/content/repositories/releases/org/tmatesoft/sqljet/sqljet/1.1.8-SNAPSHOT/maven-metadata.xml'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`
