### ISSUE TITLE
Override releaseDryRun on command line?

### ISSUE THREAD

**Issue by benfortuna** [ari/gradle-release-plugin#27]
Hi,

Is there a way override the default value configured for the releaseDryRun extension property? 

I can't find reference to such an override in the gradle forums, however it can be added to the extension implementation (i.e. reading project properties). eg:

http://gradle.1045684.n5.nabble.com/Extension-property-from-command-line-td5548804.html

 I would be happy to implement if there isn't a preferred approach for this yet.

regards,
ben

**Comment by ari** [comment]
What do you want to override? Dry run is just a boolean option which skips the commit.

**Comment by benfortuna** [comment]
I want to be able to set releaseDryRun=true in the build script, but
override it when I am actually ready to release. Otherwise I have to keep
modifying the build script manually, which doesn't really work when
automating releases, etc.

**Comment by ari** [comment]
I think you are misunderstanding how I intend for this plugin to be used. You don't need to set dryRun because you only call the 'release' target when you are actually ready to release. There is no need to change the gradle script.

**Comment by benfortuna** [comment]
Ok, so what is the purpose of dry run then? With the maven release plugin
you perform a dry run (via command line option) to ensure the release will
work ok. I guess I can live without it, but just curious as to when you
would configure a build to always perform a dry run.

**Comment by ari** [comment]
I cannot see a reason why you would configure this plugin to always perform a dry-run. That serves little purpose. All this plugin is doing for you is helping with versioning your releases, and helping with tagging. Dry-run skips the tagging part.

**Comment by benfortuna** [comment]
Ok, no worries. I was just trying to avoid editing the build script when I
needed to test the release, but guess I can temporarily change it without
committing (I'll just set allowLocalModifications=true).
